### ISSUE TITLE
Popup view controller sizing issue

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [MarioIannotta/MIBlurPopup#13]
I create my popup view controller as a separately with a xib file for reusability. It only contains an image view.

```swift
import UIKit
import MIBlurPopup

class PopupViewController: UIViewController {
    @IBOutlet weak var imageView: UIImageView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        modalPresentationCapturesStatusBarAppearance = true
    }
    
    @IBAction func didTapdismissButton(_ sender: UIButton) {
        dismiss(animated: true)
    }
    
}

// MARK: - MIBlurPopupDelegate
extension PopupViewController: MIBlurPopupDelegate {
    var popupView: UIView {
        return UIView()
    }
    
    var blurEffectStyle: UIBlurEffectStyle {
        return .dark
    }
    
    var initialScaleAmmount: CGFloat {
        return 0.7
    }
    
    var animationDuration: TimeInterval {
        return 0.3
    }
}
```

Then I show it like this.

```swift
let popupViewController = PopupViewController()
MIBlurPopup.show(popupViewController, on: self)
```

But it looks like this when displayed.

![rsz_img_6678](https://user-images.githubusercontent.com/2551877/38380847-97f116ac-3922-11e8-9b3a-078b050b6e0c.png)

The image view is supposed to have a margin of 20 from the trailing side too. But it seems to be ignoring the auto layout constraints. I can't figure out what's wrong.

I uploaded a demo project [here](https://www.dropbox.com/s/kkwgzlsuc5hqp8g/ImageModalView.zip?dl=0).

**Comment by MarioIannotta** [comment]
Hi @Isuru-Nanayakkara,
the problem here is that you're providing a new instance of `UIView` as `var popupView: UIView`.
Providing your `imageView` instead will do the trick.

```
var popupView: UIView {
  return imageView
}
```

Cheers,
Mario.

**Comment by Isuru-Nanayakkara** [comment]
Hi @MarioIannotta, I tried that. But unfortunately it didn't work either :/ [Updated source](https://www.dropbox.com/s/5vcrurhfeucf6y4/ImageModalView-updated.zip?dl=0)

**Comment by MarioIannotta** [comment]
Hi @Isuru-Nanayakkara, you're right, using an iPhone + the layout seems to be broken.
I didn't notice the issue because I was testing on a iPhone 7 :)

The issue is that after initiating the controller from the nib the size of the viewController's view is the size of the nib and not the size of your screen.

Could you please try to add those methods into your `PopupViewController`?

```
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        view.frame = UIScreen.main.bounds
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
```

Does that solve your issue?

Btw I'm not able to open your project, which Xcode version are you using?
Cheers,
Mario.

**Comment by Isuru-Nanayakkara** [comment]
Yes! That worked 👍🏼 Thank you.

I'm using Xcode 9.3 btw. The latest version.
