### ISSUE TITLE
Do not use func static show:on in objective c

### ISSUE THREAD

**Issue by PiPyL** [MarioIannotta/MIBlurPopup#14]
Do not use func static show:on in objective c

**Comment by MarioIannotta** [comment]
Hi @PiPyL, do you mind explaining a little bit better the issue you're encountering?
Can you provide a demo example?

Thanks,
Mario

**Comment by PiPyL** [comment]
@MarioIannotta thanks. i fixed it :D

**Comment by PiPyL** [comment]
i add @objc front func show on to use project objective c
