### ISSUE TITLE
SizeClass constraints aren't applied

### ISSUE THREAD

**Issue by anthonycastelli** [MarioIannotta/MIBlurPopup#15]
When setting a custom width and height for the container view in the Regular width and height size class, and pinning the sides to the top, bottom, let and right in the compact size class, things get a bit weird. 

The height constraints are completely ignored.

**Comment by MarioIannotta** [comment]
Hi Anthony,
could you please provide a simple example where I'm able to reproduce the issue?

Thank you!

**Comment by anthonycastelli** [comment]
Im out of town right now, but I will have a look when I return and see what I can cook up.
