### ISSUE TITLE
Don't have blur

### ISSUE THREAD

**Issue by PiPyL** [MarioIannotta/MIBlurPopup#16]
Hello, I have about blur in viewcontroller. Issue in example. Thanks
https://drive.google.com/open?id=1TY-jqAnzHrwcu9x5FwPn3QQogX7_0zga

**Comment by MarioIannotta** [comment]
Hi @PiPyL that's because `aViewController`'s view has a white background.
You should open `Main.storyboard` and set the `backgroundColor` to `clear` or set it through code in the `viewDidLoad`.
