### ISSUE TITLE
Can this library make dialog full screen without blur

### ISSUE THREAD

**Issue by hafiz013** [MarioIannotta/MIBlurPopup#18]
hi there, is this library can make full screen dialog without blur?

**Comment by MarioIannotta** [comment]
Hello there, 
I don't think so - if you don't need a blur and a popup I think you shouldn't use this library.

**Comment by hafiz013** [comment]
@MarioIannotta i want dialog popup with full screen like android but somewhore I couldn't get. I try adjust u sample code it almost can get full screen.

**Comment by MarioIannotta** [comment]
Well, i guess if your `popupView` has the same size of your parent view the effect would be the same. But I don't think you can remove the blur without changing the library.

**Comment by hafiz013** [comment]
is there way u can adjust the blur either make optional or compulsory.. tq @MarioIannotta

**Comment by MarioIannotta** [comment]
Released in https://github.com/MarioIannotta/MIBlurPopup/releases/tag/1.0.0
