### ISSUE TITLE
How to use MIBlurPopup without storyboard

### ISSUE THREAD

**Issue by NukanTran** [MarioIannotta/MIBlurPopup#2]

**Comment by MarioIannotta** [comment]
As described in the README file, you can present any view controller that conforms `MIBlurPopupDelegate` with this line of code:

`MIBlurPopup.show(<Any: MIBlurPopupDelegate>, on: <some view controller>)`

where 

`<Any: MIBlurPopupDelegate>` is the view controller you want to present
`<some view controller>` is the parent view controller (typically `self`)
