### ISSUE TITLE
Tabbar doesn't hide

### ISSUE THREAD

**Issue by RajChanchal** [MarioIannotta/MIBlurPopup#3]
Thanks for the MIBlurPopup. I have a little problem. When showing the popup, tabbar shows up and I am unable to hide it in popupbar view controller too.

**Comment by RajChanchal** [comment]
I have resolved this by showing the pop as:
`MIBlurPopup.show(popView, on: viewController.tabBarController!)`

i.e. presenting the pop on tabbarController

**Comment by MarioIannotta** [comment]
Hi, 
this is the expected behavior, the popup is shown above the given view controller, if you want also to hide the tab bar, you're solution will work perfectly.

Mario.
