### ISSUE TITLE
why not popup right away?

### ISSUE THREAD

**Issue by web8246** [MarioIannotta/MIBlurPopup#5]
It's really a nice 3rdParty u made.
I have a question,I have a tableview within tabbar controller. then after tableview didSelectRowAt func called. will popup the blure view. However the first time to click the cell, it works fine. but if I click other cells it will show up after quite a long time, or if I click the cell again ,then it show up. how can I fix this issue?
Thank u

**Comment by MarioIannotta** [comment]
Hi, this seems a thread issue, have you tried to force the popup show on the main thread?

**Comment by web8246** [comment]
Okay, thanks for ur advise. it works fine.Thumb!
