### ISSUE TITLE
Works with tab bar controller?

### ISSUE THREAD

**Issue by shaunjacobsen** [MarioIannotta/MIBlurPopup#7]
Hi Mario, great library here, it makes the blurred background effect really easy! I'm wondering if it's possible for it to work with a navigation tab bar controller?

I couldn't get it to work by changing the modalPresentationStyle to .full
![img_07605c426eb6-1](https://user-images.githubusercontent.com/734057/32024098-fb6404bc-b9a0-11e7-8c4a-59da3771977a.jpeg)

**Comment by MarioIannotta** [comment]
Hi Shaun, thanks :)
I don't have quite understood your question, I've embedded the source view controller in the demo in a tab bar controller and it seems to work nice.
![simulator screen shot - iphone 7 - 2017-10-26 at 20 41 08](https://user-images.githubusercontent.com/5788032/32073510-42434b48-ba8e-11e7-8923-627eef74dea1.png)
![simulator screen shot - iphone 7 - 2017-10-26 at 20 41 09](https://user-images.githubusercontent.com/5788032/32073513-42bbe04e-ba8e-11e7-8f7d-1485cb995766.png)

Could you please provide a very simple project with which I can replicate your issue?

Cheers,
Mario.

**Comment by shaunjacobsen** [comment]
Thanks for looking Mario, I was able to get it to work with some changes to my code. Cheers!

**Comment by MarioIannotta** [comment]
Great 👍
