### ISSUE TITLE
Adjust blur background on screen rotation

### ISSUE THREAD

**Issue by ghost** [MarioIannotta/MIBlurPopup#8]
How can i apply constraint instead of frame to the blur background

**Comment by MarioIannotta** [comment]
Sorry, what you mean by applying the constraint instead of frame? 
You shouldn't be able to access the blur background view and it's designed to be always big as the whole screen.

**Comment by ghost** [comment]
on device rotation the background blur frame remain the same it does not adjust to the screen rotation.

**Comment by MarioIannotta** [comment]
Fixed in MIBlurPopup 0.1.3.
If you have installed MIBlurPopup through cocoapod you should run a pod update.

**Comment by ghost** [comment]
Nice. Thank you.
